kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-8888
spec:
  podSelector:
    matchLabels:
      run: bla
  egress:
    - to:
      - ipBlock:
          cidr: 8.8.8.8/32
          